### ISSUE TITLE
Tearing chafa preview

### ISSUE THREAD

**Issue by Eitetsu0** [NikitaIvanovV/ctpv#47]
Using ctpv with lf 
![sc_20230320_02:28:04](https://user-images.githubusercontent.com/6576065/226198937-194a057f-67cd-47c8-b9e3-004b9ac518d1.png)
The original image is
![800x600](https://user-images.githubusercontent.com/6576065/226199027-baca1ccb-50cd-49c1-8e81-f168dbc7c7d8.jpg)

Any idea ?

**Comment by NikitaIvanovV** [comment]
Do you use original lf or some fork?

**Comment by Eitetsu0** [comment]
> Do you use original lf or some fork?

It's from the archlinux official repository . I believe it's the original.

.
.
Well , I removed `set autochafa` from the config file and it's not tearing now 😂 , but full filled with `?` .
![sc_20230320_11:05:27](https://user-images.githubusercontent.com/6576065/226237792-1d2ab7a9-0130-434c-a887-5949703e312f.png)


It looks good if I run `ctpv` from command line :
![sc_20230320_11:05:53](https://user-images.githubusercontent.com/6576065/226247218-6987588e-7599-4197-aef3-86519c853465.png)

**Comment by NikitaIvanovV** [comment]
Btw, I use this AUR package: https://aur.archlinux.org/packages/lf-sixel-git

**Comment by Eitetsu0** [comment]
thank you . Changing to `[lf-sixel-git](https://aur.archlinux.org/packages/lf-sixel-git)` + `[alacritty-sixel-git](https://aur.archlinux.org/packages/alacritty-sixel-git) `.
But it's still the same problem.😂 with or without `autochafa`
![sc_20230321_11:01:40](https://user-images.githubusercontent.com/6576065/226508665-0662626f-7bcf-4c29-ab05-06c70c687dc3.png)

Launch commands directly from command line looks ok .. 
![sc_20230321_11:03:09](https://user-images.githubusercontent.com/6576065/226509278-1c96d9f9-429e-4c50-8ed9-3eb1191badcb.png)
![sc_20230321_11:03:40](https://user-images.githubusercontent.com/6576065/226509287-9ac60557-e95f-4492-a628-66df3dc5004d.png)
Could force chafa to use sixel , but ctpv use char-arts anyway no matter I set `autochafa` or not.

Also according to the [README.md](https://github.com/horriblename/lf/blob/master/README.md#for-lf-users-moving-to-lf-sixel) , a previewer script works.
![sc_20230321_11:35:08](https://user-images.githubusercontent.com/6576065/226512087-b0d9570a-46b3-4157-8abd-897786e615f0.png)

**Comment by Eitetsu0** [comment]
`set chafasixel` worked normally..

char-arts tearing though.😂

**Comment by Eitetsu0** [comment]
With `set chafasixel` , ctpv displays a sixel image , which looks good and normal:
![sc_20230324_12:34:40](https://user-images.githubusercontent.com/6576065/227425518-7d56389b-8165-44a9-854f-5f384cfe1e0a.png)

By default , ctpv use char-arts to preview in terminal (i.e. `chafa -f symbols $FILENAME`) , that will somehow tearing in my system . Sreenshoot :
![sc_20230324_12:33:59](https://user-images.githubusercontent.com/6576065/227426622-bcfeecc6-17d8-46f5-a49e-30aff8ed75f2.png)

Tested with `lf` `lf-sixel` , and terminals : `alacritty` `alacritty-sixel` `termite`(vte-based) `xterm` . It doesn't seem like terminal related.

**Comment by Eitetsu0** [comment]
I think its because the `WIDTH` ctpv received  is  smaller than the actual preview window and the line wrapped.

**Comment by NikitaIvanovV** [comment]
I pushed a test change to a new branch: `test-lf-width`. Could you please test it?

**Comment by Eitetsu0** [comment]
> I pushed a test change to a new branch: `test-lf-width`. Could you please test it?

Tested , still the same problem.

By the way , the command line script for testing , in case any missing :
```sh
~/p/source/ctpv test-lf-width ?1 ❯ export XDG_CONFIG_HOME=/tmp
~/p/source/ctpv test-lf-width ?1 ❯ cat lfrc
set previewer ~/p/source/ctpv/ctpv
set cleaner ~/p/source/ctpv/ctpvclear
&~/p/source/ctpv/ctpv -s $id
&~/p/source/ctpv/ctpvquit $id
~/p/source/ctpv test-lf-width ?1 ❯ lf -config lfrc ~/Picture/chakra-wallpapers-giau-master/800x600.jpg
```
